export enum STATUS_CONFIG {
    NOT_ACTIVE_LABEL = "Not Active",
    NOT_ACTIVE_VALUE = "NOT_ACTIVE",
    PENDING_ACTIVE_LABEL = "Pending Active",
    PENDING_ACTIVE_VALUE = "PENDING_ACTIVE",
    ACTIVATED_LABEL = "Activated",
    ACTIVATED_VALUE = "ACTIVATED",
}
export enum USER_TYPE {
    ADMIN = "ADMIN",
    AGENT = "AGENT",
    DISTRIBUTOR = "DISTRIBUTOR",
    PARTNER = "PARTNER",
    CUSTOMER = "CUSTOMER"
}

export enum STATUS_AGENT {
    NOT_ACTIVE_LABEL = "Not Active",
    NOT_ACTIVE_VALUE = "NOT_ACTIVE",
    ACTIVATED_LABEL = "Activated",
    ACTIVATED_VALUE = "ACTIVATED",
}
export enum ROLES {
    ADMIN = "ADMIN",
    AGENT = "AGENT",
    DISTRIBUTOR = "DISTRIBUTOR",
    PARTNER = "PARTNER",
    CUSTOMER = "CUSTOMER"
}