export enum STATUS_CONFIG {
    NOT_ACTIVE = "NOT_ACTIVE",
    PENDING_ACTIVE = "PENDING_ACTIVE",
    ACTIVATED = "ACTIVATED"
}
export enum USER_TYPE {
    ADMIN = "ADMIN",
    AGENT = "AGENT",
    DISTRIBUTOR = "DISTRIBUTOR",
    PARTNER = "PARTNER",
    CUSTOMER = "CUSTOMER"
}

export enum STATUS_AGENT {
    NOT_ACTIVE = "NOT_ACTIVE",
    ACTIVATED = "ACTIVATED"
}